// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB2y5-plg-2wmUlt0NDOum9tgUGAwBDPws',
    appId: '1:390106081788:web:04dcabcb135c218ff7ea79',
    messagingSenderId: '390106081788',
    projectId: 'notnetflix-flutter',
    authDomain: 'notnetflix-flutter.firebaseapp.com',
    storageBucket: 'notnetflix-flutter.appspot.com',
    measurementId: 'G-6FB9T5ZXKN',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA3AlIeYQ_xZe346mcbaysWnFopxQlSREc',
    appId: '1:390106081788:android:a394e9651b9d6e72f7ea79',
    messagingSenderId: '390106081788',
    projectId: 'notnetflix-flutter',
    storageBucket: 'notnetflix-flutter.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDjc8UTIGuv3EzILhUsuIgKbyfpwqoBLSQ',
    appId: '1:390106081788:ios:e1a95f4634f8ad83f7ea79',
    messagingSenderId: '390106081788',
    projectId: 'notnetflix-flutter',
    storageBucket: 'notnetflix-flutter.appspot.com',
    iosClientId: '390106081788-9mq4eb4qt63o29c73fc6ve2oe6dgebd9.apps.googleusercontent.com',
    iosBundleId: 'com.not-netflix.app',
  );
}
